### ISSUE TITLE
Can you help me in kuaishou!

### ISSUE THREAD

**Issue by kakaka6c** [biubiuww/spider#3]
I can't run script. Can you help me. I want to download videos nowatermark from Kuaishou

**Comment by biubiuww** [comment]
> I can't run script. Can you help me. I want to download videos nowatermark from Kuaishou

 fix the bugs in Kuaishou.

**Comment by kakaka6c** [comment]
Do you know how to  access Kuaishou in another country, coz my PC can't see any videos in kuaishou channel. I logined...

**Comment by kakaka6c** [comment]
http://127.0.0.1:9910/get/
Now I can't access to it. Can you help me ?

**Comment by biubiuww** [comment]
> http://127.0.0.1:9910/get/
> Now I can't access to it. Can you help me ?

you need proxy pool~[Proxy pool](https://github.com/jhao104/proxy_pool)

If you don't have. Cancel proxy settings in ./kuaishou/lib/crawler.py

**Comment by kakaka6c** [comment]
ah no, This script is download in feed ?
Can you help me download all videos in channel ?

**Comment by kakaka6c** [comment]
Thank you before <3
